package decision.rules

import com.i2i.drools.HelloWorldExample.Message;
 
rule "Hello World"
    when
        m : Message( status == Message.HELLO, message : message )
    then
        System.out.println( message + " - SUCCESSFUL !!!" );
end

rule "Good Bye"
    when
        Message( status == Message.GOODBYE, message : message )
    then
        System.out.println( message );
end